spring.application.name=mywedding

spring.datasource.url=jdbc:mysql://localhost:3306

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

cloudinary.cloud-name=dgzsteyut
cloudinary-api-key=927731122919737
cloudinary.api-secret=DEncNUEYEBbsuyKkVZVkxNQad34


